import type { Employee } from "@/components/company-detail/employee-column";
import type { RowData } from "@/components/dashboard/columns";

export const rows: RowData[] = [
  {
    id: "728ed52f",
    company_name: "Acme Corp",
    email: "m@example.com",
    password: "password123",
    owner_name: "Michael Scott",
    owner_email: "michael.scott@acme.com",
    company_type: "Private Limited",
    website: "https://acme.com",
    contact_number: "+1 212-555-0100",
    company_address: "123 Main St, New York, NY",
    description: "Leading provider of innovative solutions.",
    technology: "Software House",
  },
  {
    id: "489e1d42",
    company_name: "Techify LLC",
    email: "example@gmail.com",
    password: "techify@123",
    owner_name: "Sophia Turner",
    owner_email: "sophia.turner@techify.com",
    company_type: "LLC",
    website: "https://techify.com",
    contact_number: "+1 415-555-0123",
    company_address: "456 Market St, San Francisco, CA",
    description: "Technology solutions for modern businesses.",
    technology: "Restaurant",
  },
  {
    id: "a13fd91b",
    company_name: "Globex Industries",
    email: "john.doe@example.com",
    password: "globex#2025",
    owner_name: "John Doe",
    owner_email: "john.doe@globex.com",
    company_type: "Corporation",
    website: "https://globex.com",
    contact_number: "+1 312-555-0456",
    company_address: "789 Industrial Rd, Chicago, IL",
    description: "Global leader in industrial manufacturing.",
    technology: "Hotel",
  },
  {
    id: "c82bf71e",
    company_name: "InnoSoft Ltd",
    email: "sara.smith@example.com",
    password: "innosoft!dev",
    owner_name: "Sara Smith",
    owner_email: "sara.smith@innosoft.com",
    company_type: "Limited",
    website: "https://innosoft.com",
    contact_number: "+1 512-555-0789",
    company_address: "321 Innovation Ave, Austin, TX",
    description: "Innovative software development company.",
    technology: "E-Commerce",
  },
  {
    id: "d47ac23a",
    company_name: "NextGen Systems",
    email: "alex.jones@example.com",
    password: "nextgen#it",
    owner_name: "Alex Jones",
    owner_email: "alex.jones@nextgensys.com",
    company_type: "Private",
    website: "https://nextgensys.com",
    contact_number: "+1 206-555-0912",
    company_address: "654 Future Blvd, Seattle, WA",
    description: "Building next-generation IT systems.",
    technology: "Construction",
  },
  {
    id: "f29ed91c",
    company_name: "Visionary Labs",
    email: "linda.williams@example.com",
    password: "vision2025",
    owner_name: "Linda Williams",
    owner_email: "linda.williams@visionlabs.com",
    company_type: "Research Lab",
    website: "https://visionlabs.com",
    contact_number: "+1 617-555-0147",
    company_address: "987 Research Park, Boston, MA",
    description: "Research-driven technology lab.",
    technology: "Healthcare",
  },
  {
    id: "e51cd84b",
    company_name: "Skyline Solutions",
    email: "david.lee@example.com",
    password: "skyline*dev",
    owner_name: "David Lee",
    owner_email: "david.lee@skylinesol.com",
    company_type: "IT Services",
    website: "https://skylinesol.com",
    contact_number: "+1 303-555-0169",
    company_address: "159 Skyline Dr, Denver, CO",
    description: "Providing cutting-edge cloud solutions.",
    technology: "Education",
  },
  {
    id: "g62ef12d",
    company_name: "BrightPath Co.",
    email: "emma.brown@example.com",
    password: "bright@2025",
    owner_name: "Emma Brown",
    owner_email: "emma.brown@brightpath.com",
    company_type: "Partnership",
    website: "https://brightpath.com",
    contact_number: "+1 407-555-0198",
    company_address: "753 Bright St, Orlando, FL",
    description: "Guiding businesses to brighter futures.",
    technology: "Travel Agency",
  },
  {
    id: "h73kd91x",
    company_name: "Pioneer Tech",
    email: "pioneer@example.com",
    password: "pioneer!tech",
    owner_name: "James Carter",
    owner_email: "james.carter@pioneert.com",
    company_type: "Private",
    website: "https://pioneert.com",
    contact_number: "+1 214-555-0213",
    company_address: "852 Explorer Rd, Dallas, TX",
    description: "Pioneering innovative tech solutions.",
    technology: "Real Estate",
  },
  {
    id: "i84mf02y",
    company_name: "SummitWorks",
    email: "summit@example.com",
    password: "summit#work",
    owner_name: "Olivia Green",
    owner_email: "olivia.green@summitworks.com",
    company_type: "Limited",
    website: "https://summitworks.com",
    contact_number: "+1 385-555-0255",
    company_address: "963 Summit Ave, Salt Lake City, UT",
    description: "Helping clients reach their business peak.",
    technology: "Logistics",
  },

  // ✅ 15 more dummy rows
  {
    id: "j95ng13z",
    company_name: "MetroBank Inc",
    email: "contact@metrobank.com",
    password: "metro#bank",
    owner_name: "William Parker",
    owner_email: "william.parker@metrobank.com",
    company_type: "Corporation",
    website: "https://metrobank.com",
    contact_number: "+1 646-555-0301",
    company_address: "111 Wall St, New York, NY",
    description: "Trusted banking solutions for enterprises.",
    technology: "Banking",
  },
  {
    id: "k06ph24a",
    company_name: "FreshMart",
    email: "info@freshmart.com",
    password: "fresh@mart",
    owner_name: "Chloe Adams",
    owner_email: "chloe.adams@freshmart.com",
    company_type: "Private",
    website: "https://freshmart.com",
    contact_number: "+1 702-555-0314",
    company_address: "222 Green St, Las Vegas, NV",
    description: "Retail supermarket chain.",
    technology: "Retail",
  },
  {
    id: "l17qr35b",
    company_name: "CityCare Hospital",
    email: "support@citycare.com",
    password: "citycare#2025",
    owner_name: "Ethan Martinez",
    owner_email: "ethan.martinez@citycare.com",
    company_type: "Limited",
    website: "https://citycare.com",
    contact_number: "+1 718-555-0328",
    company_address: "333 Health Ave, Brooklyn, NY",
    description: "Quality healthcare for all.",
    technology: "Hospital",
  },
  {
    id: "m28rs46c",
    company_name: "EcoEnergy Ltd",
    email: "eco@ecoenergy.com",
    password: "eco!power",
    owner_name: "Sophia Clark",
    owner_email: "sophia.clark@ecoenergy.com",
    company_type: "Corporation",
    website: "https://ecoenergy.com",
    contact_number: "+1 505-555-0339",
    company_address: "444 Solar Way, Albuquerque, NM",
    description: "Sustainable energy solutions.",
    technology: "Energy",
  },
  {
    id: "n39st57d",
    company_name: "Oceanic Travels",
    email: "travel@oceanic.com",
    password: "oceanic#2025",
    owner_name: "Daniel Kim",
    owner_email: "daniel.kim@oceanic.com",
    company_type: "Partnership",
    website: "https://oceanictravels.com",
    contact_number: "+1 310-555-0345",
    company_address: "555 Beach Blvd, Los Angeles, CA",
    description: "Travel agency specializing in cruises.",
    technology: "Hospitality",
  },
  {
    id: "o40uv68e",
    company_name: "PrimeLogix",
    email: "info@primelogix.com",
    password: "prime#logix",
    owner_name: "Emma Wilson",
    owner_email: "emma.wilson@primelogix.com",
    company_type: "LLC",
    website: "https://primelogix.com",
    contact_number: "+1 214-555-0361",
    company_address: "666 Cargo Rd, Dallas, TX",
    description: "Global logistics and supply chain company.",
    technology: "Transport",
  },
  {
    id: "p51wx79f",
    company_name: "EduSmart",
    email: "hello@edusmart.com",
    password: "edu@smart",
    owner_name: "Isabella Harris",
    owner_email: "isabella.harris@edusmart.com",
    company_type: "Private",
    website: "https://edusmart.com",
    contact_number: "+1 407-555-0372",
    company_address: "777 Learning St, Orlando, FL",
    description: "E-learning solutions for modern schools.",
    technology: "EdTech",
  },
  {
    id: "q62xy80g",
    company_name: "FarmFresh Foods",
    email: "farm@freshfoods.com",
    password: "farmfresh@2025",
    owner_name: "Benjamin White",
    owner_email: "benjamin.white@freshfoods.com",
    company_type: "Private",
    website: "https://farmfresh.com",
    contact_number: "+1 515-555-0389",
    company_address: "888 Farm Rd, Des Moines, IA",
    description: "Organic food production company.",
    technology: "Agriculture",
  },
  {
    id: "r73yz91h",
    company_name: "StreamLine Media",
    email: "media@streamline.com",
    password: "stream#2025",
    owner_name: "Mia Johnson",
    owner_email: "mia.johnson@streamline.com",
    company_type: "Corporation",
    website: "https://streamline.com",
    contact_number: "+1 917-555-0395",
    company_address: "999 Media Plaza, New York, NY",
    description: "Digital media and streaming services.",
    technology: "Media",
  },
  {
    id: "s84za02i",
    company_name: "SafeHome Security",
    email: "support@safehome.com",
    password: "safe@2025",
    owner_name: "Jacob Davis",
    owner_email: "jacob.davis@safehome.com",
    company_type: "LLC",
    website: "https://safehome.com",
    contact_number: "+1 602-555-0407",
    company_address: "1010 Secure Ln, Phoenix, AZ",
    description: "Home and business security systems.",
    technology: "Security",
  },
  {
    id: "t95ab13j",
    company_name: "AquaWorld",
    email: "contact@aquaworld.com",
    password: "aqua#2025",
    owner_name: "Charlotte Moore",
    owner_email: "charlotte.moore@aquaworld.com",
    company_type: "Partnership",
    website: "https://aquaworld.com",
    contact_number: "+1 305-555-0418",
    company_address: "1111 Ocean Dr, Miami, FL",
    description: "Aquatic theme parks and resorts.",
    technology: "Entertainment",
  },
  {
    id: "u06bc24k",
    company_name: "BuildRight",
    email: "info@buildright.com",
    password: "build@2025",
    owner_name: "Henry Thompson",
    owner_email: "henry.thompson@buildright.com",
    company_type: "Private",
    website: "https://buildright.com",
    contact_number: "+1 212-555-0425",
    company_address: "1212 Builder Ave, New York, NY",
    description: "Construction and real estate services.",
    technology: "Infrastructure",
  },
  {
    id: "v17cd35l",
    company_name: "FinTrust",
    email: "support@fintrust.com",
    password: "fintrust#2025",
    owner_name: "Amelia Walker",
    owner_email: "amelia.walker@fintrust.com",
    company_type: "Corporation",
    website: "https://fintrust.com",
    contact_number: "+1 312-555-0438",
    company_address: "1313 Finance St, Chicago, IL",
    description: "Investment and wealth management.",
    technology: "Finance",
  },
  {
    id: "w28de46m",
    company_name: "StyleHub",
    email: "hello@stylehub.com",
    password: "style@2025",
    owner_name: "Harper Lewis",
    owner_email: "harper.lewis@stylehub.com",
    company_type: "LLC",
    website: "https://stylehub.com",
    contact_number: "+1 213-555-0442",
    company_address: "1414 Fashion Ave, Los Angeles, CA",
    description: "Online fashion retail platform.",
    technology: "Fashion",
  },
  {
    id: "x39ef57n",
    company_name: "GreenLeaf",
    email: "contact@greenleaf.com",
    password: "green@leaf",
    owner_name: "Alexander Martinez",
    owner_email: "alex.martinez@greenleaf.com",
    company_type: "Private",
    website: "https://greenleaf.com",
    contact_number: "+1 919-555-0456",
    company_address: "1515 Eco Blvd, Raleigh, NC",
    description: "Eco-friendly product manufacturing.",
    technology: "Environment",
  },
  {
    id: "y40fg68o",
    company_name: "NextGen AI",
    email: "ai@nextgen.com",
    password: "nextgen@ai",
    owner_name: "Victoria Scott",
    owner_email: "victoria.scott@nextgen.com",
    company_type: "Corporation",
    website: "https://nextgenai.com",
    contact_number: "+1 408-555-0467",
    company_address: "1616 Tech Valley, San Jose, CA",
    description: "AI and ML-driven solutions.",
    technology: "Artificial Intelligence",
  },
  {
    id: "z51gh79p",
    company_name: "Foodies Delight",
    email: "hello@foodies.com",
    password: "foodie@2025",
    owner_name: "Logan Rivera",
    owner_email: "logan.rivera@foodies.com",
    company_type: "Partnership",
    website: "https://foodies.com",
    contact_number: "+1 512-555-0479",
    company_address: "1717 Gourmet St, Austin, TX",
    description: "Fast food and fine dining services.",
    technology: "Food & Beverage",
  },
];

export const employees: Employee[] = [
  {
    id: "1",
    name: "John Doe",
    email: "m@example.com",
    password: "password123",
    website: "https://example.com",
    technology: "React, Node.js",
    phone: "+1-123-456-7890",
    role: "CEO",
    designation: "Chief Executive Officer",
    department: "Management",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "example@gmail.com",
    password: "password456",
    website: "https://ui-designs.com",
    technology: "Figma, Tailwind, React",
    phone: "+1-222-333-4444",
    role: "CTO",
    designation: "Chief Technology Officer",
    department: "Technology",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "example@example.com",
    password: "password789",
    website: "https://product-mgmt.com",
    technology: "Agile, Scrum, Jira",
    phone: "+1-555-666-7777",
    role: "Product Manager",
    designation: "Senior Product Manager",
    department: "Product",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    password: "pass123",
    website: "https://emilydavis.dev",
    technology: "React, TypeScript, Express",
    phone: "+1-111-222-3333",
    role: "Employee",
    designation: "Full Stack Developer",
    department: "Engineering",
  },
  {
    id: "5",
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    password: "pass456",
    website: "https://danlee.io",
    technology: "Node.js, AWS, Docker",
    phone: "+1-444-555-6666",
    role: "Employee",
    designation: "Backend Developer",
    department: "Engineering",
  },
  {
    id: "6",
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    password: "pass789",
    website: "https://sophiamartinez.com",
    technology: "Vue.js, Nuxt, Tailwind",
    phone: "+1-777-888-9999",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "7",
    name: "William Brown",
    email: "will.b@example.com",
    password: "pass321",
    website: "https://williamb.dev",
    technology: "PostgreSQL, MongoDB, MySQL",
    phone: "+1-222-444-8888",
    role: "Employee",
    designation: "Database Administrator",
    department: "Engineering",
  },
  {
    id: "8",
    name: "Olivia Wilson",
    email: "olivia.w@example.com",
    password: "pass654",
    website: "https://oliviawilson.design",
    technology: "Figma, Adobe XD, Sketch",
    phone: "+1-555-123-4567",
    role: "Employee",
    designation: "UI/UX Designer",
    department: "Design",
  },
  {
    id: "9",
    name: "James Taylor",
    email: "james.t@example.com",
    password: "pass987",
    website: "https://jamestaylor.io",
    technology: "Kubernetes, Jenkins, Terraform",
    phone: "+1-888-999-0000",
    role: "Employee",
    designation: "DevOps Engineer",
    department: "Infrastructure",
  },
  {
    id: "10",
    name: "Ava Anderson",
    email: "ava.a@example.com",
    password: "pass111",
    website: "https://avaanderson.com",
    technology: "Cypress, Jest, Selenium",
    phone: "+1-333-222-1111",
    role: "Employee",
    designation: "QA Engineer",
    department: "Quality Assurance",
  },
  {
    id: "11",
    name: "Michael Thomas",
    email: "michael.t@example.com",
    password: "pass222",
    website: "https://michaelthomas.dev",
    technology: "React, Redux, Next.js",
    phone: "+1-123-321-4567",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "12",
    name: "Isabella Garcia",
    email: "isabella.g@example.com",
    password: "pass333",
    website: "https://isabellagarcia.design",
    technology: "Photoshop, Illustrator, Figma",
    phone: "+1-456-789-1234",
    role: "Employee",
    designation: "Graphic Designer",
    department: "Design",
  },
  {
    id: "13",
    name: "Benjamin Harris",
    email: "ben.h@example.com",
    password: "pass444",
    website: "https://benharris.io",
    technology: "Azure, AWS, GCP",
    phone: "+1-654-321-9876",
    role: "Employee",
    designation: "Cloud Architect",
    department: "Infrastructure",
  },
  {
    id: "14",
    name: "Mia Clark",
    email: "mia.c@example.com",
    password: "pass555",
    website: "https://miaclark.dev",
    technology: "Swift, Kotlin, Flutter",
    phone: "+1-987-654-3210",
    role: "Employee",
    designation: "Mobile Developer",
    department: "Engineering",
  },
  {
    id: "15",
    name: "Ethan Lewis",
    email: "ethan.l@example.com",
    password: "pass666",
    website: "https://ethanlewis.dev",
    technology: "Python, TensorFlow, PyTorch",
    phone: "+1-741-852-9630",
    role: "Employee",
    designation: "Machine Learning Engineer",
    department: "AI/ML",
  },
  {
    id: "16",
    name: "Charlotte Walker",
    email: "charlotte.w@example.com",
    password: "pass777",
    website: "https://charlottewalker.design",
    technology: "Illustrator, Photoshop, Figma",
    phone: "+1-963-852-7410",
    role: "Employee",
    designation: "Brand Designer",
    department: "Design",
  },
  {
    id: "17",
    name: "Alexander King",
    email: "alex.k@example.com",
    password: "pass888",
    website: "https://alexking.dev",
    technology: "SIEM, Firewalls, Pen Testing",
    phone: "+1-852-456-1597",
    role: "Employee",
    designation: "Cybersecurity Analyst",
    department: "Security",
  },
  {
    id: "18",
    name: "Amelia Scott",
    email: "amelia.s@example.com",
    password: "pass999",
    website: "https://ameliascott.design",
    technology: "After Effects, Blender, Premiere",
    phone: "+1-753-951-4563",
    role: "Employee",
    designation: "Motion Designer",
    department: "Design",
  },
  {
    id: "19",
    name: "Lucas Young",
    email: "lucas.y@example.com",
    password: "pass000",
    website: "https://lucasyoung.dev",
    technology: "Next.js, Vercel, Lighthouse",
    phone: "+1-159-357-8520",
    role: "Employee",
    designation: "Performance Engineer",
    department: "Engineering",
  },
  {
    id: "20",
    name: "Harper Allen",
    email: "harper.a@example.com",
    password: "pass101",
    website: "https://harperallen.io",
    technology: "Markdown, Notion, Confluence",
    phone: "+1-258-654-1479",
    role: "Employee",
    designation: "Technical Writer",
    department: "Documentation",
  },
  {
    id: "21",
    name: "Henry Hall",
    email: "henry.h@example.com",
    password: "pass202",
    website: "https://henryhall.dev",
    technology: "Angular, TypeScript, RxJS",
    phone: "+1-369-258-1470",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "22",
    name: "Evelyn Green",
    email: "evelyn.g@example.com",
    password: "pass303",
    website: "https://evelyngreen.com",
    technology: "SEO, Google Ads, Analytics",
    phone: "+1-951-753-4567",
    role: "Employee",
    designation: "SEO Specialist",
    department: "Marketing",
  },
  {
    id: "23",
    name: "Jack Adams",
    email: "jack.a@example.com",
    password: "pass404",
    website: "https://jackadams.dev",
    technology: "Java, Spring Boot, Hibernate",
    phone: "+1-852-159-3570",
    role: "Employee",
    designation: "Java Developer",
    department: "Engineering",
  },
];
