import type { Employee } from "@/components/company-detail/employee-column";

export const employees: Employee[] = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    position: "Chief Executive Officer",
    salary: 150000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    position: "Chief Technology Officer",
    salary: 140000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "3",
    first_name: "Bob",
    last_name: "Johnson",
    email: "bob.johnson@example.com",
    position: "Senior Product Manager",
    salary: 120000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "4",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily.davis@example.com",
    position: "Full Stack Developer",
    salary: 95000,
    is_candidate: false,
    company_id: "489e1d42",
  },
  {
    id: "5",
    first_name: "Daniel",
    last_name: "Lee",
    email: "daniel.lee@example.com",
    position: "Backend Developer",
    salary: 90000,
    is_candidate: false,
    company_id: "489e1d42",
  },
  {
    id: "6",
    first_name: "Sophia",
    last_name: "Martinez",
    email: "sophia.martinez@example.com",
    position: "Frontend Developer",
    salary: 88000,
    is_candidate: false,
    company_id: "a13fd91b",
  },
  {
    id: "7",
    first_name: "William",
    last_name: "Brown",
    email: "william.brown@example.com",
    position: "Database Administrator",
    salary: 85000,
    is_candidate: false,
    company_id: "a13fd91b",
  },
  {
    id: "8",
    first_name: "Olivia",
    last_name: "Wilson",
    email: "olivia.wilson@example.com",
    position: "UI/UX Designer",
    salary: 80000,
    is_candidate: false,
    company_id: "c82bf71e",
  },
  {
    id: "9",
    first_name: "James",
    last_name: "Taylor",
    email: "james.taylor@example.com",
    position: "DevOps Engineer",
    salary: 110000,
    is_candidate: false,
    company_id: "c82bf71e",
  },
  {
    id: "10",
    first_name: "Ava",
    last_name: "Anderson",
    email: "ava.anderson@example.com",
    position: "QA Engineer",
    salary: 75000,
    is_candidate: false,
    company_id: "d47ac23a",
  },
  {
    id: "11",
    first_name: "Michael",
    last_name: "Thomas",
    email: "michael.thomas@example.com",
    position: "Frontend Developer",
    salary: 92000,
    is_candidate: false,
    company_id: "d47ac23a",
  },
  {
    id: "12",
    first_name: "Isabella",
    last_name: "Garcia",
    email: "isabella.garcia@example.com",
    position: "Graphic Designer",
    salary: 70000,
    is_candidate: false,
    company_id: "f29ed91c",
  },
  {
    id: "13",
    first_name: "Benjamin",
    last_name: "Harris",
    email: "benjamin.harris@example.com",
    position: "Cloud Architect",
    salary: 130000,
    is_candidate: false,
    company_id: "f29ed91c",
  },
  {
    id: "14",
    first_name: "Mia",
    last_name: "Clark",
    email: "mia.clark@example.com",
    position: "Mobile Developer",
    salary: 95000,
    is_candidate: false,
    company_id: "e51cd84b",
  },
  {
    id: "15",
    first_name: "Ethan",
    last_name: "Lewis",
    email: "ethan.lewis@example.com",
    position: "Machine Learning Engineer",
    salary: 120000,
    is_candidate: false,
    company_id: "e51cd84b",
  },
  {
    id: "16",
    first_name: "Charlotte",
    last_name: "Walker",
    email: "charlotte.walker@example.com",
    position: "Brand Designer",
    salary: 75000,
    is_candidate: false,
    company_id: "g62ef12d",
  },
  {
    id: "17",
    first_name: "Alexander",
    last_name: "King",
    email: "alexander.king@example.com",
    position: "Cybersecurity Analyst",
    salary: 100000,
    is_candidate: false,
    company_id: "g62ef12d",
  },
  {
    id: "18",
    first_name: "Amelia",
    last_name: "Scott",
    email: "amelia.scott@example.com",
    position: "Motion Designer",
    salary: 78000,
    is_candidate: false,
    company_id: "h73kd91x",
  },
  {
    id: "19",
    first_name: "Lucas",
    last_name: "Young",
    email: "lucas.young@example.com",
    position: "Performance Engineer",
    salary: 105000,
    is_candidate: false,
    company_id: "h73kd91x",
  },
  {
    id: "20",
    first_name: "Harper",
    last_name: "Allen",
    email: "harper.allen@example.com",
    position: "Technical Writer",
    salary: 65000,
    is_candidate: false,
    company_id: "i84mf02y",
  },
  {
    id: "21",
    first_name: "Henry",
    last_name: "Hall",
    email: "henry.hall@example.com",
    position: "Frontend Developer",
    salary: 90000,
    is_candidate: false,
    company_id: "i84mf02y",
  },
  {
    id: "22",
    first_name: "Evelyn",
    last_name: "Green",
    email: "evelyn.green@example.com",
    position: "SEO Specialist",
    salary: 68000,
    is_candidate: false,
    company_id: "j95ng13z",
  },
  {
    id: "23",
    first_name: "Jack",
    last_name: "Adams",
    email: "jack.adams@example.com",
    position: "Java Developer",
    salary: 87000,
    is_candidate: false,
    company_id: "j95ng13z",
  },
  {
    id: "24",
    first_name: "Sarah",
    last_name: "Miller",
    email: "sarah.miller@example.com",
    position: "Marketing Manager",
    salary: 75000,
    is_candidate: true,
    company_id: "k06ph24a",
  },
  {
    id: "25",
    first_name: "David",
    last_name: "Wilson",
    email: "david.wilson@example.com",
    position: "Sales Director",
    salary: 110000,
    is_candidate: true,
    company_id: "l17qr35b",
  },
];

export const policies = [
  {
    title: "Innovation First",
    description: "We encourage creativity and innovative thinking in all aspects of work.",
  },
  {
    title: "Collaboration",
    description: "Teamwork and open communication are key to building a strong culture.",
  },
  {
    title: "Integrity",
    description: "We act with honesty, fairness, and transparency in all situations.",
  },
  {
    title: "Continuous Learning",
    description: "We support professional growth and learning for all team members.",
  },
  {
    title: "Work-Life Balance",
    description: "We value mental health and ensure balance between work and personal life.",
  },
];
