import type { Employee } from "@/components/company-detail/employee-column";
import type { RowData } from "@/types";

export const rows: RowData[] = [
  {
    id: "728ed52f",
    company_name: "Acme Corp",
    email: "m@example.com",
    password: "password123",
    owner_name: "Michael Scott",
    owner_email: "michael.scott@acme.com",
    company_type: "Private Limited",
    website: "https://acme.com",
    contact_number: "+1 212-555-0100",
    company_address: "123 Main St, New York, NY",
    description: "Leading provider of innovative solutions.",
    technology: "Software House",
  },
  {
    id: "489e1d42",
    company_name: "Techify LLC",
    email: "example@gmail.com",
    password: "techify@123",
    owner_name: "Sophia Turner",
    owner_email: "sophia.turner@techify.com",
    company_type: "LLC",
    website: "https://techify.com",
    contact_number: "+1 415-555-0123",
    company_address: "456 Market St, San Francisco, CA",
    description: "Technology solutions for modern businesses.",
    technology: "Restaurant",
  },
  {
    id: "a13fd91b",
    company_name: "Globex Industries",
    email: "john.doe@example.com",
    password: "globex#2025",
    owner_name: "John Doe",
    owner_email: "john.doe@globex.com",
    company_type: "Corporation",
    website: "https://globex.com",
    contact_number: "+1 312-555-0456",
    company_address: "789 Industrial Rd, Chicago, IL",
    description: "Global leader in industrial manufacturing.",
    technology: "Hotel",
  },
  {
    id: "c82bf71e",
    company_name: "InnoSoft Ltd",
    email: "sara.smith@example.com",
    password: "innosoft!dev",
    owner_name: "Sara Smith",
    owner_email: "sara.smith@innosoft.com",
    company_type: "Limited",
    website: "https://innosoft.com",
    contact_number: "+1 512-555-0789",
    company_address: "321 Innovation Ave, Austin, TX",
    description: "Innovative software development company.",
    technology: "E-Commerce",
  },
  {
    id: "d47ac23a",
    company_name: "NextGen Systems",
    email: "alex.jones@example.com",
    password: "nextgen#it",
    owner_name: "Alex Jones",
    owner_email: "alex.jones@nextgensys.com",
    company_type: "Private",
    website: "https://nextgensys.com",
    contact_number: "+1 206-555-0912",
    company_address: "654 Future Blvd, Seattle, WA",
    description: "Building next-generation IT systems.",
    technology: "Construction",
  },
  {
    id: "f29ed91c",
    company_name: "Visionary Labs",
    email: "linda.williams@example.com",
    password: "vision2025",
    owner_name: "Linda Williams",
    owner_email: "linda.williams@visionlabs.com",
    company_type: "Research Lab",
    website: "https://visionlabs.com",
    contact_number: "+1 617-555-0147",
    company_address: "987 Research Park, Boston, MA",
    description: "Research-driven technology lab.",
    technology: "Healthcare",
  },
  {
    id: "e51cd84b",
    company_name: "Skyline Solutions",
    email: "david.lee@example.com",
    password: "skyline*dev",
    owner_name: "David Lee",
    owner_email: "david.lee@skylinesol.com",
    company_type: "IT Services",
    website: "https://skylinesol.com",
    contact_number: "+1 303-555-0169",
    company_address: "159 Skyline Dr, Denver, CO",
    description: "Providing cutting-edge cloud solutions.",
    technology: "Education",
  },
  {
    id: "g62ef12d",
    company_name: "BrightPath Co.",
    email: "emma.brown@example.com",
    password: "bright@2025",
    owner_name: "Emma Brown",
    owner_email: "emma.brown@brightpath.com",
    company_type: "Partnership",
    website: "https://brightpath.com",
    contact_number: "+1 407-555-0198",
    company_address: "753 Bright St, Orlando, FL",
    description: "Guiding businesses to brighter futures.",
    technology: "Travel Agency",
  },
  {
    id: "h73kd91x",
    company_name: "Pioneer Tech",
    email: "pioneer@example.com",
    password: "pioneer!tech",
    owner_name: "James Carter",
    owner_email: "james.carter@pioneert.com",
    company_type: "Private",
    website: "https://pioneert.com",
    contact_number: "+1 214-555-0213",
    company_address: "852 Explorer Rd, Dallas, TX",
    description: "Pioneering innovative tech solutions.",
    technology: "Real Estate",
  },
  {
    id: "i84mf02y",
    company_name: "SummitWorks",
    email: "summit@example.com",
    password: "summit#work",
    owner_name: "Olivia Green",
    owner_email: "olivia.green@summitworks.com",
    company_type: "Limited",
    website: "https://summitworks.com",
    contact_number: "+1 385-555-0255",
    company_address: "963 Summit Ave, Salt Lake City, UT",
    description: "Helping clients reach their business peak.",
    technology: "Logistics",
  },
  {
    id: "j95ng13z",
    company_name: "MetroBank Inc",
    email: "contact@metrobank.com",
    password: "metro#bank",
    owner_name: "William Parker",
    owner_email: "william.parker@metrobank.com",
    company_type: "Corporation",
    website: "https://metrobank.com",
    contact_number: "+1 646-555-0301",
    company_address: "111 Wall St, New York, NY",
    description: "Trusted banking solutions for enterprises.",
    technology: "Banking",
  },
  {
    id: "k06ph24a",
    company_name: "FreshMart",
    email: "info@freshmart.com",
    password: "fresh@mart",
    owner_name: "Chloe Adams",
    owner_email: "chloe.adams@freshmart.com",
    company_type: "Private",
    website: "https://freshmart.com",
    contact_number: "+1 702-555-0314",
    company_address: "222 Green St, Las Vegas, NV",
    description: "Retail supermarket chain.",
    technology: "Retail",
  },
  {
    id: "l17qr35b",
    company_name: "CityCare Hospital",
    email: "support@citycare.com",
    password: "citycare#2025",
    owner_name: "Ethan Martinez",
    owner_email: "ethan.martinez@citycare.com",
    company_type: "Limited",
    website: "https://citycare.com",
    contact_number: "+1 718-555-0328",
    company_address: "333 Health Ave, Brooklyn, NY",
    description: "Quality healthcare for all.",
    technology: "Hospital",
  },
  {
    id: "m28rs46c",
    company_name: "EcoEnergy Ltd",
    email: "eco@ecoenergy.com",
    password: "eco!power",
    owner_name: "Sophia Clark",
    owner_email: "sophia.clark@ecoenergy.com",
    company_type: "Corporation",
    website: "https://ecoenergy.com",
    contact_number: "+1 505-555-0339",
    company_address: "444 Solar Way, Albuquerque, NM",
    description: "Sustainable energy solutions.",
    technology: "Energy",
  },
  {
    id: "n39st57d",
    company_name: "Oceanic Travels",
    email: "travel@oceanic.com",
    password: "oceanic#2025",
    owner_name: "Daniel Kim",
    owner_email: "daniel.kim@oceanic.com",
    company_type: "Partnership",
    website: "https://oceanictravels.com",
    contact_number: "+1 310-555-0345",
    company_address: "555 Beach Blvd, Los Angeles, CA",
    description: "Travel agency specializing in cruises.",
    technology: "Hospitality",
  },
  {
    id: "o40uv68e",
    company_name: "PrimeLogix",
    email: "info@primelogix.com",
    password: "prime#logix",
    owner_name: "Emma Wilson",
    owner_email: "emma.wilson@primelogix.com",
    company_type: "LLC",
    website: "https://primelogix.com",
    contact_number: "+1 214-555-0361",
    company_address: "666 Cargo Rd, Dallas, TX",
    description: "Global logistics and supply chain company.",
    technology: "Transport",
  },
  {
    id: "p51wx79f",
    company_name: "EduSmart",
    email: "hello@edusmart.com",
    password: "edu@smart",
    owner_name: "Isabella Harris",
    owner_email: "isabella.harris@edusmart.com",
    company_type: "Private",
    website: "https://edusmart.com",
    contact_number: "+1 407-555-0372",
    company_address: "777 Learning St, Orlando, FL",
    description: "E-learning solutions for modern schools.",
    technology: "EdTech",
  },
  {
    id: "q62xy80g",
    company_name: "FarmFresh Foods",
    email: "farm@freshfoods.com",
    password: "farmfresh@2025",
    owner_name: "Benjamin White",
    owner_email: "benjamin.white@freshfoods.com",
    company_type: "Private",
    website: "https://farmfresh.com",
    contact_number: "+1 515-555-0389",
    company_address: "888 Farm Rd, Des Moines, IA",
    description: "Organic food production company.",
    technology: "Agriculture",
  },
  {
    id: "r73yz91h",
    company_name: "StreamLine Media",
    email: "media@streamline.com",
    password: "stream#2025",
    owner_name: "Mia Johnson",
    owner_email: "mia.johnson@streamline.com",
    company_type: "Corporation",
    website: "https://streamline.com",
    contact_number: "+1 917-555-0395",
    company_address: "999 Media Plaza, New York, NY",
    description: "Digital media and streaming services.",
    technology: "Media",
  },
  {
    id: "s84za02i",
    company_name: "SafeHome Security",
    email: "support@safehome.com",
    password: "safe@2025",
    owner_name: "Jacob Davis",
    owner_email: "jacob.davis@safehome.com",
    company_type: "LLC",
    website: "https://safehome.com",
    contact_number: "+1 602-555-0407",
    company_address: "1010 Secure Ln, Phoenix, AZ",
    description: "Home and business security systems.",
    technology: "Security",
  },
  {
    id: "t95ab13j",
    company_name: "AquaWorld",
    email: "contact@aquaworld.com",
    password: "aqua#2025",
    owner_name: "Charlotte Moore",
    owner_email: "charlotte.moore@aquaworld.com",
    company_type: "Partnership",
    website: "https://aquaworld.com",
    contact_number: "+1 305-555-0418",
    company_address: "1111 Ocean Dr, Miami, FL",
    description: "Aquatic theme parks and resorts.",
    technology: "Entertainment",
  },
  {
    id: "u06bc24k",
    company_name: "BuildRight",
    email: "info@buildright.com",
    password: "build@2025",
    owner_name: "Henry Thompson",
    owner_email: "henry.thompson@buildright.com",
    company_type: "Private",
    website: "https://buildright.com",
    contact_number: "+1 212-555-0425",
    company_address: "1212 Builder Ave, New York, NY",
    description: "Construction and real estate services.",
    technology: "Infrastructure",
  },
  {
    id: "v17cd35l",
    company_name: "FinTrust",
    email: "support@fintrust.com",
    password: "fintrust#2025",
    owner_name: "Amelia Walker",
    owner_email: "amelia.walker@fintrust.com",
    company_type: "Corporation",
    website: "https://fintrust.com",
    contact_number: "+1 312-555-0438",
    company_address: "1313 Finance St, Chicago, IL",
    description: "Investment and wealth management.",
    technology: "Finance",
  },
  {
    id: "w28de46m",
    company_name: "StyleHub",
    email: "hello@stylehub.com",
    password: "style@2025",
    owner_name: "Harper Lewis",
    owner_email: "harper.lewis@stylehub.com",
    company_type: "LLC",
    website: "https://stylehub.com",
    contact_number: "+1 213-555-0442",
    company_address: "1414 Fashion Ave, Los Angeles, CA",
    description: "Online fashion retail platform.",
    technology: "Fashion",
  },
  {
    id: "x39ef57n",
    company_name: "GreenLeaf",
    email: "contact@greenleaf.com",
    password: "green@leaf",
    owner_name: "Alexander Martinez",
    owner_email: "alex.martinez@greenleaf.com",
    company_type: "Private",
    website: "https://greenleaf.com",
    contact_number: "+1 919-555-0456",
    company_address: "1515 Eco Blvd, Raleigh, NC",
    description: "Eco-friendly product manufacturing.",
    technology: "Environment",
  },
  {
    id: "y40fg68o",
    company_name: "NextGen AI",
    email: "ai@nextgen.com",
    password: "nextgen@ai",
    owner_name: "Victoria Scott",
    owner_email: "victoria.scott@nextgen.com",
    company_type: "Corporation",
    website: "https://nextgenai.com",
    contact_number: "+1 408-555-0467",
    company_address: "1616 Tech Valley, San Jose, CA",
    description: "AI and ML-driven solutions.",
    technology: "Artificial Intelligence",
  },
  {
    id: "z51gh79p",
    company_name: "Foodies Delight",
    email: "hello@foodies.com",
    password: "foodie@2025",
    owner_name: "Logan Rivera",
    owner_email: "logan.rivera@foodies.com",
    company_type: "Partnership",
    website: "https://foodies.com",
    contact_number: "+1 512-555-0479",
    company_address: "1717 Gourmet St, Austin, TX",
    description: "Fast food and fine dining services.",
    technology: "Food & Beverage",
  },
];

export const employees: Employee[] = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    position: "Chief Executive Officer",
    salary: 150000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    position: "Chief Technology Officer",
    salary: 140000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "3",
    first_name: "Bob",
    last_name: "Johnson",
    email: "bob.johnson@example.com",
    position: "Senior Product Manager",
    salary: 120000,
    is_candidate: false,
    company_id: "728ed52f",
  },
  {
    id: "4",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily.davis@example.com",
    position: "Full Stack Developer",
    salary: 95000,
    is_candidate: false,
    company_id: "489e1d42",
  },
  {
    id: "5",
    first_name: "Daniel",
    last_name: "Lee",
    email: "daniel.lee@example.com",
    position: "Backend Developer",
    salary: 90000,
    is_candidate: false,
    company_id: "489e1d42",
  },
  {
    id: "6",
    first_name: "Sophia",
    last_name: "Martinez",
    email: "sophia.martinez@example.com",
    position: "Frontend Developer",
    salary: 88000,
    is_candidate: false,
    company_id: "a13fd91b",
  },
  {
    id: "7",
    first_name: "William",
    last_name: "Brown",
    email: "william.brown@example.com",
    position: "Database Administrator",
    salary: 85000,
    is_candidate: false,
    company_id: "a13fd91b",
  },
  {
    id: "8",
    first_name: "Olivia",
    last_name: "Wilson",
    email: "olivia.wilson@example.com",
    position: "UI/UX Designer",
    salary: 80000,
    is_candidate: false,
    company_id: "c82bf71e",
  },
  {
    id: "9",
    first_name: "James",
    last_name: "Taylor",
    email: "james.taylor@example.com",
    position: "DevOps Engineer",
    salary: 110000,
    is_candidate: false,
    company_id: "c82bf71e",
  },
  {
    id: "10",
    first_name: "Ava",
    last_name: "Anderson",
    email: "ava.anderson@example.com",
    position: "QA Engineer",
    salary: 75000,
    is_candidate: false,
    company_id: "d47ac23a",
  },
  {
    id: "11",
    first_name: "Michael",
    last_name: "Thomas",
    email: "michael.thomas@example.com",
    position: "Frontend Developer",
    salary: 92000,
    is_candidate: false,
    company_id: "d47ac23a",
  },
  {
    id: "12",
    first_name: "Isabella",
    last_name: "Garcia",
    email: "isabella.garcia@example.com",
    position: "Graphic Designer",
    salary: 70000,
    is_candidate: false,
    company_id: "f29ed91c",
  },
  {
    id: "13",
    first_name: "Benjamin",
    last_name: "Harris",
    email: "benjamin.harris@example.com",
    position: "Cloud Architect",
    salary: 130000,
    is_candidate: false,
    company_id: "f29ed91c",
  },
  {
    id: "14",
    first_name: "Mia",
    last_name: "Clark",
    email: "mia.clark@example.com",
    position: "Mobile Developer",
    salary: 95000,
    is_candidate: false,
    company_id: "e51cd84b",
  },
  {
    id: "15",
    first_name: "Ethan",
    last_name: "Lewis",
    email: "ethan.lewis@example.com",
    position: "Machine Learning Engineer",
    salary: 120000,
    is_candidate: false,
    company_id: "e51cd84b",
  },
  {
    id: "16",
    first_name: "Charlotte",
    last_name: "Walker",
    email: "charlotte.walker@example.com",
    position: "Brand Designer",
    salary: 75000,
    is_candidate: false,
    company_id: "g62ef12d",
  },
  {
    id: "17",
    first_name: "Alexander",
    last_name: "King",
    email: "alexander.king@example.com",
    position: "Cybersecurity Analyst",
    salary: 100000,
    is_candidate: false,
    company_id: "g62ef12d",
  },
  {
    id: "18",
    first_name: "Amelia",
    last_name: "Scott",
    email: "amelia.scott@example.com",
    position: "Motion Designer",
    salary: 78000,
    is_candidate: false,
    company_id: "h73kd91x",
  },
  {
    id: "19",
    first_name: "Lucas",
    last_name: "Young",
    email: "lucas.young@example.com",
    position: "Performance Engineer",
    salary: 105000,
    is_candidate: false,
    company_id: "h73kd91x",
  },
  {
    id: "20",
    first_name: "Harper",
    last_name: "Allen",
    email: "harper.allen@example.com",
    position: "Technical Writer",
    salary: 65000,
    is_candidate: false,
    company_id: "i84mf02y",
  },
  {
    id: "21",
    first_name: "Henry",
    last_name: "Hall",
    email: "henry.hall@example.com",
    position: "Frontend Developer",
    salary: 90000,
    is_candidate: false,
    company_id: "i84mf02y",
  },
  {
    id: "22",
    first_name: "Evelyn",
    last_name: "Green",
    email: "evelyn.green@example.com",
    position: "SEO Specialist",
    salary: 68000,
    is_candidate: false,
    company_id: "j95ng13z",
  },
  {
    id: "23",
    first_name: "Jack",
    last_name: "Adams",
    email: "jack.adams@example.com",
    position: "Java Developer",
    salary: 87000,
    is_candidate: false,
    company_id: "j95ng13z",
  },
  {
    id: "24",
    first_name: "Sarah",
    last_name: "Miller",
    email: "sarah.miller@example.com",
    position: "Marketing Manager",
    salary: 75000,
    is_candidate: true,
    company_id: "k06ph24a",
  },
  {
    id: "25",
    first_name: "David",
    last_name: "Wilson",
    email: "david.wilson@example.com",
    position: "Sales Director",
    salary: 110000,
    is_candidate: true,
    company_id: "l17qr35b",
  },
];

export const policies = [
  {
    title: "Innovation First",
    description: "We encourage creativity and innovative thinking in all aspects of work.",
  },
  {
    title: "Collaboration",
    description: "Teamwork and open communication are key to building a strong culture.",
  },
  {
    title: "Integrity",
    description: "We act with honesty, fairness, and transparency in all situations.",
  },
  {
    title: "Continuous Learning",
    description: "We support professional growth and learning for all team members.",
  },
  {
    title: "Work-Life Balance",
    description: "We value mental health and ensure balance between work and personal life.",
  },
];
